
CREATE DATABASE converse CHARACTER SET utf8 COLLATE utf8_general_ci;

USE converse;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(150) NOT NULL,
  first_name VARCHAR(40) NULL,
  middle_name VARCHAR(40) NULL,
  last_name VARCHAR(40) NULL,
  dob DATE NULL,
  balance INT NOT NULL DEFAULT 0,
  last_logged_in DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_email_addresses (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED  NOT NULL,
  email_address VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id)  REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_languages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  language INT DEFAULT NULL,
  level INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id)  REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_lessons (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  lesson_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_phone_numbers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  area_code SMALLINT NOT NULL,
  number INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE admin_messages (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_notifications (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  admin_message_id SMALLINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (admin_message_id) REFERENCES admin_messages(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE devices (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  device_key VARCHAR(100) NOT NULL,
  make VARCHAR(40) NOT NULL,
  model VARCHAR(40) NOT NULL,
  height SMALLINT UNSIGNED NOT NULL,
  width SMALLINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id),
  UNIQUE(device_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_devices (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  device_id INT UNSIGNED NOT NULL,
  ip_address_v4 VARCHAR(15) NOT NULL,
  ip_address_v6 VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_tokens (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  token VARCHAR(255) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  user_device_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_device_id) REFERENCES user_devices(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE (token),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE versions (
  version VARCHAR(18) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_available_lesson_downloads (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  lesson_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE settings (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  token VARCHAR(50) NOT NULL,
  value TEXT NOT NULL,
  description VARCHAR(255) NOT NULL,
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id),
  UNIQUE (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO settings (token, value, description, locked) VALUES ('jwt-key', 'tqMXXVpivC10l697Kva5-BBYahL102uLgZvy3awLY-AbdIYhXRBUCXxFFov9iC-iZXv4n3pOH2amVRGuYqO', 'jwt key', TRUE),
                                                                ('salt-key', 'f92\38fhj/e890322%309rgj$ka#wk3235jg98£w23jh!g459%n3wt', 'Password salt do not change unless you want to break all the save passwords', TRUE),
                                                                ('log-path', '/var/log/converse/', 'The path that logs will be saved in', FALSE);

DELIMITER ;;
CREATE TRIGGER settings_update_RO_trigger BEFORE UPDATE ON settings FOR EACH ROW
  IF OLD.locked THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot update locked record';
  END IF;;

CREATE TRIGGER settings_delete_RO_trigger BEFORE DELETE ON settings FOR EACH ROW
  IF OLD.locked THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot delete locked record';
  END IF;;
DELIMITER ;
